[project]
name = "blueswede"
requires-python = ">=3.9"
description = "Utilities for working with ANUGA."
keywords = []
authors = [
    { name = "Andrew Moodie", email = "amoodie@tamu.edu" },
    { name = "Texas A&M Surface Processes"},
]
maintainers = [
    { name = "Andrew Moodie", email = "amoodie@tamu.edu" },
    { name = "Texas A&M Surface Processes"},
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Hydrology",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "importlib-resources; python_version < '3.12'",
    "matplotlib",
    "anuga",
    "scipy",
    "netCDF4",
    "numpy"
]
dynamic = [
    "version",
    "readme",
]

[project.license]
text = "MIT"

[project.urls]
homepage = "https://github.com/tamu-surface-processes/blueswede"
repository = "https://github.com/tamu-surface-processes/blueswede"

[project.optional-dependencies]
testing = [
    "pytest",
]

[build-system]
requires = [
    "setuptools >=61",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic.readme]
file = "README.rst"
content-type = "text/x-rst"

[tool.setuptools.dynamic.version]
attr = "blueswede._version._version"

[tool.setuptools.packages.find]
where = [
    ".",
]
include = [
    "blueswede*",
]

[tool.coverage.run]
relative_files = true

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = [
    "tests",
]
norecursedirs = [
    ".*",
    "*.egg*",
    "build",
    "dist",
    "test_data"
]
addopts = [
    "--ignore=setup.py",
    "--tb=native",
    "--durations=16",
    "--strict-markers",
    "--doctest-modules",
    "-vvv",
]
